name: SAP CF APP保活

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

concurrency:
  group: keepalive
  cancel-in-progress: true

jobs:
  keepalive:
    runs-on: ubuntu-latest
    timeout-minutes: 8

    steps:
      - name: Force stop app first
        uses: docker://cloudfoundry/cf-cli:latest
        with:
          args: run cf api ${{ secrets.CF_API }} && cf login -u ${{ secrets.CF_USERNAME }} -p ${{ secrets.CF_PASSWORD }} -o ${{ secrets.CF_ORG }} -s ${{ secrets.CF_SPACE }} -a && cf stop ${{ secrets.CF_APP }}

      - name: KeepAlive via container
        uses: docker://ghcr.io/uncleluogithub/cf-keepalive:latest
        env:
          CF_USERNAME: ${{ secrets.CF_USERNAME }}
          CF_PASSWORD: ${{ secrets.CF_PASSWORD }}
          CF_API: ${{ secrets.CF_API }}
          CF_ORG: ${{ secrets.CF_ORG }}
          CF_SPACE: ${{ secrets.CF_SPACE }}
          CF_APP: ${{ secrets.CF_APP }}
          CF_SET_PROCESS_HC: "true"
